# Generated by Django 4.2.9 on 2025-12-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('communication', 'Communication'), ('productivity', 'Productivity'), ('design', 'Design'), ('development', 'Development'), ('project_management', 'Project Management'), ('other', 'Other')], default='other', max_length=50)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool Link',
                'verbose_name_plural': 'Tool Links',
                'db_table': 'tool_links',
                'ordering': ['name'],
            },
        ),
    ]
