# Generated by Django 4.2.9 on 2025-12-27 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toollinks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='toollinks.toollink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool Favorite',
                'verbose_name_plural': 'Tool Favorites',
                'db_table': 'tool_favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tool')},
            },
        ),
    ]
