# Generated by Django 4.2.9 on 2025-12-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toollinks', '0003_toolfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollink',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
