# Generated by Django 4.2.9 on 2025-12-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toollinks', '0004_alter_toollink_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolfavorite',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Tool Favorite', 'verbose_name_plural': 'Tool Favorites'},
        ),
        migrations.AddField(
            model_name='toolfavorite',
            name='order',
            field=models.IntegerField(default=0, help_text='User-defined order for displaying favorites'),
        ),
    ]
