# Generated by Django 4.2.9 on 2025-12-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toollinks', '0005_alter_toolfavorite_options_toolfavorite_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='toollink',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='If True, this tool is only visible to the creator'),
        ),
    ]
