# Generated by Django 4.2.9 on 2025-12-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toollinks', '0006_toollink_is_personal'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='toolfavorite',
            index=models.Index(fields=['user', 'order'], name='tool_favori_user_id_d54176_idx'),
        ),
        migrations.AddIndex(
            model_name='toolfavorite',
            index=models.Index(fields=['user', 'tool'], name='tool_favori_user_id_a9d591_idx'),
        ),
        migrations.AddIndex(
            model_name='toollink',
            index=models.Index(fields=['is_active', 'is_personal', 'created_by_id'], name='tool_links_is_acti_46dbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='toollink',
            index=models.Index(fields=['category', 'is_active'], name='tool_links_categor_582c36_idx'),
        ),
        migrations.AddIndex(
            model_name='toollink',
            index=models.Index(fields=['name'], name='tool_links_name_f62c5d_idx'),
        ),
    ]
