# Generated by Django 4.2.9 on 2025-12-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link related to the task', max_length=500, null=True),
        ),
    ]
