# Generated by Django 4.2.9 on 2025-12-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
