# Generated by Django 4.2.9 on 2025-12-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('ocean', 'Ocean Blue'), ('forest', 'Forest Green'), ('sunset', 'Sunset')], default='light', help_text='User selected color theme', max_length=20),
        ),
    ]
