# Generated by Django 4.2.9 on 2025-12-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='tools_category_labels',
            field=models.JSONField(blank=True, default=dict, help_text='Custom labels for tool categories. Maps category keys to custom display names.'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('ocean', 'Ocean Blue'), ('metro', 'MetroShoe'), ('sunset', 'Sunset')], default='light', help_text='User selected color theme', max_length=20),
        ),
    ]
