# Generated by Django 4.2.9 on 2025-12-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_tools_category_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='tools_category_colors',
            field=models.JSONField(blank=True, default=dict, help_text='Custom colors for tool categories. Maps category keys to hex color codes (e.g., "#3B82F6").'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='tools_category_labels',
            field=models.JSONField(blank=True, default=dict, help_text='Custom labels for tool categories. Maps category keys to custom display names. Does NOT modify tool.category values.'),
        ),
    ]
