# Generated by Django 4.2.9 on 2025-12-27 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userpreferences_clock_mood_widgets'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the leave')),
                ('end_date', models.DateField(help_text='End date of the leave')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal'), ('other', 'Other')], default='vacation', help_text='Type of leave', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason or description for the leave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Schedule',
                'verbose_name_plural': 'Leave Schedules',
                'db_table': 'leave_schedules',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'start_date'], name='leave_sched_user_id_0ecab1_idx'), models.Index(fields=['start_date', 'end_date'], name='leave_sched_start_d_c14729_idx')],
            },
        ),
    ]
