# Generated by Django 4.2.9 on 2025-12-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_leaveschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='custom_widgets',
            field=models.JSONField(blank=True, default=dict, help_text='Custom widgets: {"widget_id": {"title": "...", "html": "...", "css": "..."}}'),
        ),
    ]
