# Generated by Django 4.2.9 on 2025-12-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userpreferences_custom_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='alarm_widget_alarms',
            field=models.JSONField(blank=True, default=list, help_text='Alarm list: [{"id": "...", "time": "HH:MM", "label": "...", "enabled": true, "repeat": ["mon", "tue"], "sound": "default"}, ...]'),
        ),
    ]
